### ISSUE TITLE
Battle System Test

### ISSUE THREAD

**Issue by SodaCookie** [SodaCookie/RPG-Game#3]
We require a battle system test to see how well our code can integrate the classes Player, Monster and Move into a pseudo-battle system.
- [x] Setup the variables required (List of monsters, list of players, etc...)
- [x] Setup the game loop that takes into delta time
  - [x] The game must pause whenever a player is ready
    - [x] Simply execute a move that the user types in
  - [x] When a monster is ready, simply do an attack

**Comment by hollahollabooya** [comment]
Completed
