### ISSUE TITLE
Integrate Level Up UI

### ISSUE THREAD

**Issue by hollahollabooya** [SodaCookie/RPG-Game#50]
The level up UI has been developed, gotta hook it up to the game engine

**Comment by SodaCookie** [comment]
- [x] Determine what widgets are necessary
- [x] Refactor the base classes and add abstractions as necessary
- [x] Reimplement interfaces
- [x] Move BattleManager out of "Managers" as it is not a collection of Renderables

**Comment by SodaCookie** [comment]
Level Up UI is finished
